workspace:
  base: /go
  path: src/github.com/go-training/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  测试:
    image: golang:1.9
    pull: true
    commands:
      - make fmt-check
      - go vet
      - go test -v .
    when:
      event: tag
      ref: refs/tags/reg*

  build_linux_amd64:
    image: golang:1.9
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -a -o release/linux/amd64/helloworld

  build_linux_i386:
    image: golang:1.9
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=386
    commands:
      - go build -v -a -o release/linux/amd64/helloworld

  publish_server:
    image: plugins/docker
    pull: true
    repo: appleboy/helloworld
    secrets: [ docker_username, docker_password ]
    default_tags: true
    when:
      event: [ push, tag ]
